### ISSUE TITLE
[node:nid] token does not work

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/auto_nodetitle#26]
I was trying to use the [node:nid] token in an auto generated title and it's not working. Also tried [node:original:nid] and that did not work. 

I tried to use [node:nid] in the auto generated path and that worked fine. 

I'm doing this on a fresh Backdrop 1.10.0 site.

**Comment by stpaultim** [comment]
I checked the issue queue for the Drupal version of the this module and there are a number of issues addressing this question. 
https://www.drupal.org/project/issues/search/auto_nodetitle?text=nid

It appears that the module is unable to use the NID token, because until the node is saved the nid does not exist. That had occurred to me, except that I tested the NID token in the auto generated path and it seems to work there. That is what is confusing to me. 

This is not a critical issue to me. Just frustrating, because the token appears to be available but does not work.

NOTE: My goal was to have some unique number in the title, NID seemed like a convenient option. I could use some custom date format as well.

**Comment by quicksketch** [comment]
This module saves the title in `hook_node_presave()`, which is before a NID is assigned. Unfortunately because the `nid` and the `title` are both saved in the same `node` table, you'd have to write to the table twice in order put the NID in the title (once to get the NID assigned, and then another time to save the title with the NID in it). It's possible to achieve this by also implementing `hook_node_insert()` and `hook_node_update()` (which happen _after_ the initial node save), but at the same time I don't think end-users would ever suspect that using `[node:nid]` tokens would require double-writing to the database. Maybe that would matter to them, maybe it wouldn't.

**Comment by robertgarrigos** [comment]
Looking into this, I realized that you only need to clear the cache to have the title with the nid, I don't understand why....

**Comment by argiepiano** [comment]
One option (if you are using this module only for this case) is to disable this module and implement hook_node_insert to set the title the first time the node is saved. You can put this in a custom module, or template.php (haven't tested placing in template.php)

This may look like this (put in a custom module)
```php
function MY_MODULE_NAME_node_insert($node) {
  $node->title = t('My node id is !id', array('!id' => $node->id()));
  $node->is_new = FALSE;
  $node->save();
}
```

**Comment by argiepiano** [comment]
Edited my post - using hook_node_update() the way I had it will cause an infinite loop.

**Comment by danksearle** [comment]
I have a similar problem, but instead of the NID we are trying to insert another value into the title. My symptoms were: on first saving the node the title was wrong, the value was missing. If I clear the cache, then the title was shown correctly. The title is also corrected by editing and saving the node again. To see the title, I am viewing the node in its view URL and looking at the browser tab. 

I have also observed that the node title when shown in the admin contents list is shown as I want, correctly. However, if I use the devel module to view the node field values, and look at the title field, it is shown badly, with the value missing. Pretty weird! It seems that the admin/contents list shows titles without using the cache, whereas devel uses cached data. 

Anyway, I believe this can be fixed with this patch to the auto_nodetitle module, to clear the cache for the node when it saves the title at the end of auto_nodetitle_set_title().

```
diff --git a/modules/auto_nodetitle/auto_nodetitle.module b/modules/auto_nodetitle/auto_nodetitle.module
index 92681737..9546dd7c 100644
--- a/modules/auto_nodetitle/auto_nodetitle.module
+++ b/modules/auto_nodetitle/auto_nodetitle.module
@@ -143,6 +143,9 @@ function auto_nodetitle_set_title(&$node) {
   // With that flag we ensure we don't apply the title two times to the same
   // node. See auto_nodetitle_is_needed().
   $node->auto_nodetitle_applied = TRUE;
+
+  // Clear the cache for the affected node.
+  entity_get_controller('node')->resetCache(array($node->nid));
 }
 
 /**
```

[auto_nodetitle_clear_node_cache.patch](https://github.com/backdrop-contrib/auto_nodetitle/files/13205933/auto_nodetitle_clear_node_cache.patch)

**Comment by robertgarrigos** [comment]
Thanks, @danksearle, this patch fixes this problem.
