### ISSUE TITLE
Default should be disabled on form

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/auto_nodetitle#33]
When creating a new content type the form defaults to not having any of the options selected. It should default to Disabled. I'm not completely sure but I think it might be messing with content types where it isn't set.

**Comment by quicksketch** [comment]
PR filed at https://github.com/backdrop-contrib/auto_nodetitle/pull/40

The current behavior doesn't seem to do any harm other than being confusing. A value of 0 or a value of NULL both result in no automatic node titles being generated. But it is confusing have radio buttons with an empty default. My PR just casts NULL to 0 so an option is selected, but this could be made into a more comprehensive fix where no data is saved at all if it is disabled (leave it NULL instead of saving a zero). But this simple fix leaves in place the current behavior while just fixing the default on the form.
