### ISSUE TITLE
Conflict with Preview feature

### ISSUE THREAD

**Issue by oriolroger** [backdrop-contrib/auto_nodetitle#47]
Hi, we have this module enabled and the core Preview feature active for a content type (option "Preview before submitting").

If we Preview a node, and instead of saving we click on Back to content, then the node form is displayed again, but it gets out of date, and when we try to save or preview it again, the error "The content on this page has either been modified by another user, or you have already submitted modifications using this form. As a result, your changes cannot be saved" is fired.

This is because in the _function auto_nodetitle_node_submit_, there's a new command `backdrop_register_shutdown_function('_auto_nodetitle_save_title');` that changes the title of the node and updates the 'changed' column in the node table, when we are in the Preview page, even before saving the node.

Not sure why this call to backdrop_register_shutdown_function is needed, it was not in Drupal 7. If we comment it out, then all the Preview process is working correctly.

Thanks.

**Comment by argiepiano** [comment]
This line was introduced in the dev version of D7. See this [line](https://git.drupalcode.org/project/auto_nodetitle/-/blob/7.x-1.x/auto_nodetitle.module?ref_type=heads#L81).

The issue is explained here: https://www.drupal.org/project/auto_nodetitle/issues/1910016

This allows people to use the node ID in a token for the title of the node. Effectively, the title is changed  and saved during the shutdown process, after the node has been saved. 

So... there has to be another way of solving your problem. I don't know what it is. Removing the line in question will effectively mangle the ability to use nid in the title.

**Comment by robertgarrigos** [comment]
I found myself in situations, related to other modules (even with core), where the preview feature was more of a problem than a help. My solution has always been to advise my users to save a draft to see how they will see their post. Safer also.
