### ISSUE TITLE
VBO update action has no result

### ISSUE THREAD

**Issue by rtola-wpc** [backdrop-contrib/auto_nodetitle#48]
Many thanks for making this module available to the Backdrop community. It's very powerful and does exactly what I need.

I see it's available as an action in Views Bulk Operations, listed as an action as "Update automatic nodetitles". Unfortunately, I'm not getting this to work, and there are no relevant messages in the error log. (Backdrop version 1.27.0, this module version 1.x-1.0.7) I have ~ 2k nodes to process, but testing with just one, reveals the update failure.

I can trigger the desired functionality by saving each node one at a time, but nothing happens through the VBO route.

**Comment by argiepiano** [comment]
For this action to work with VBO, it needs to be adjusted slightly. VBO in Backdrop uses hook_vboaction_info(). The action defined by the nodetitle module follows the syntax for the core Bulk Actions, and obviously is not working properly.

**Comment by rtola-wpc** [comment]
Adjusting that is beyond my skill set. I wonder if someone would be willing to take that on? With ~ 200 active installs, this might be greatly valued.

**Comment by argiepiano** [comment]
It looks like this Bulk action was added to the Backdrop version of the module (it does not exist in Drupal 7). Unfortunately the code is faulty. I'll submit a PR.

BTW you don't really need to install the contrib Views Bulk Operations. When fixed, this Bulk action will work with the Bulk Operations provided in Backdrop's core.

**Comment by argiepiano** [comment]
@rtola-wpc, I have submitted a PR. Can you test it? It's very simple. You'll need to patch the module in order to test.

To test:
1. Be sure your auto_nodetitle settings for the content type is "Automatically generate the title and hide the title field". If you have "Automatically generate the title if the title field is left empty", this will no regenerate the title, since the title already exists for the nodes (since this is a View, those nodes have been saved already and the title has been generated).
2. You don't really need the contrib version of VBO. You can use the core's Bulk operations. BUT it should still work if you try to run the action within VBO

**Comment by rtola-wpc** [comment]
@argiepiano, This works whichever way I set it (run from within VBO). Thank you.

I need these nodes to display the title, so I selected "Automatically generate the title if the title field is left empty", but it also worked with "Automatically generate the title and hide the title field".
